### ISSUE TITLE
增加全局默认配置

### ISSUE THREAD

**Issue by lqzhgood** [heyongsheng/hevue-img-preview#16]
例如我想全局关闭 keyboard 现在需要在每个调用的地方都要传  keyboard: 'close'

现有的模式是 默认配置都硬编码在代码里了，最好是有 defaultConfig ，这样可以通过修改 defaultConfig 达到全局配置的目的。

 keyboard: 'open' / 'close' 不太优雅吧。

```
keyboard: true / false  // vue props 里面记得加校验

option.keyboard !== undefined ? option.keyboard : defaultConfig.keyboard 
```

**Comment by heyongsheng** [comment]
OK。谢谢建议，我回去思考下怎么写

**Comment by heyongsheng** [comment]
你好，建议已采纳，现版本已增加全局配置项，使用文档已更新

**Comment by lqzhgood** [comment]
##### 建议
相同大版本号下的新版本应该兼容旧版本。即3.5.0升级到3.6.0时API不应该发生变化。 不应该有 break change

<hr />
const state = a || false  默认值只能为 false

**Comment by heyongsheng** [comment]
谢谢建议🌹🌹🌹，确实基础较差😞😞😞，这些都不怎么懂，以后会不断的补充相关知识的😀😀😀

**Comment by heyongsheng** [comment]
另外3.6.0版本有问题，我已经更新到3.6.2了
