### ISSUE TITLE
打开预览后，浏览器后退不会关闭

### ISSUE THREAD

**Issue by HeatonZ** [heyongsheng/hevue-img-preview#28]
能否加个控制关闭的方法，或者是获取实例的方法

**Comment by heyongsheng** [comment]
这个问题我倒是没有想过，回头试一下

**Comment by heyongsheng** [comment]
你好，这个问题已经优化，版本号为5.0.2，可以安装后尝试一下
![image](https://user-images.githubusercontent.com/18118447/147340512-0bdd1f4b-b5e2-479b-9a7f-dd5cdeec233d.png)
