### ISSUE TITLE
本地图片直接放url不行，需要使用require先导入图片

### ISSUE THREAD

**Issue by phm-front** [heyongsheng/hevue-img-preview#29]
const urlArr = this.detailInfo.fj.map(item => {
    return require(`@/assets/images/fj/${item}`)
  })
  this.$hevueImgPreview({
    multiple: true, // 开启多图预览模式
    nowImgIndex: index, // 多图预览，默认展示第二张图片
    imgList: urlArr, // 需要预览的多图数组
  })

**Comment by heyongsheng** [comment]
是的，这个问题我忽略了 ，后续会对文档进行修改，感谢支持
