### ISSUE TITLE
only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by wait-for-the-wind** [heyongsheng/hevue-img-preview#3]
我本地已经装过babel-polyfill了， 怎么兼容啊。。。 包里面的能单独去掉嘛

**Comment by 0x0ffff** [comment]
一样遇到的问题，多个引入的导致冲突了。

**Comment by 0x0ffff** [comment]
> 我本地已经装过babel-polyfill了， 怎么兼容啊。。。 包里面的能单独去掉嘛

我在这里找到了解决方法。

https://github.com/babel/babel-loader/issues/401/#issuecomment-365650944

**Comment by heyongsheng** [comment]
我已经删除了包内置的babel-polyfill，如果有任何问题欢迎随时联系
