### ISSUE TITLE
层级问题

### ISSUE THREAD

**Issue by Geoffyscat** [heyongsheng/hevue-img-preview#31]
目前遇到的问题是，我在dialog中调用，饿了吗UI  会出现层级问题。哪怕我深度选择设置z-index也不会在第一层。求助

**Comment by heyongsheng** [comment]
已经很久没有收到您的反馈了，希望这个解决方案可以帮到您，这个issue我就先关闭了，如有任何问题欢迎新提issue，感谢您的支持
