### ISSUE TITLE
多图预览报错

### ISSUE THREAD

**Issue by aline9543** [heyongsheng/hevue-img-preview#5]
![未命名1605597881](https://user-images.githubusercontent.com/51693939/99358789-fe5d8e80-28e8-11eb-8546-c4c3f7de70e6.png)
![未命名1605597907](https://user-images.githubusercontent.com/51693939/99358794-fef62500-28e8-11eb-8796-e2ad7bcdd300.png)

**Comment by heyongsheng** [comment]
你好，方便的话可以加一下我微信沟通一下
heyongsheng1996
