### ISSUE TITLE
不支持移动端吗

### ISSUE THREAD

**Issue by Orangec765** [heyongsheng/hevue-img-preview#7]

**Comment by heyongsheng** [comment]
对，暂时没考虑移动端

**Comment by Orangec765** [comment]
有没有什么建议吗  如果做移动端的话

**Comment by heyongsheng** [comment]
思路都一样把，手机端点击图片，然后调用这个方法，只不过里面的布局可能要适配一下移动端，还有鼠标滚动事件要改成双指缩放，全图/复原可以用双击事件触发，鼠标移动事件改为手指移动，逻辑方面应该是通用的

**Comment by Orangec765** [comment]
问题是点了没反应在手机上你这个插件

**Comment by heyongsheng** [comment]
所以你可以直接下载源码修改一下------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;CC&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月21日(星期一) 晚上6:54
收件人:&nbsp;&quot;heyongsheng/hevue-img-preview&quot;<hevue-img-preview@noreply.github.com&gt;;
抄送:&nbsp;&quot;heyongsheng&quot;<1378431028@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [heyongsheng/hevue-img-preview] 不支持移动端吗 (#7)

**Comment by Orangec765** [comment]
2296900942@qq.com 发来我看看谢谢

**Comment by heyongsheng** [comment]
Github上不就是源码吗😂------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;CC&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月21日(星期一) 晚上7:01
收件人:&nbsp;&quot;heyongsheng/hevue-img-preview&quot;<hevue-img-preview@noreply.github.com&gt;;
抄送:&nbsp;&quot;heyongsheng&quot;<1378431028@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [heyongsheng/hevue-img-preview] 不支持移动端吗 (#7)

**Comment by heyongsheng** [comment]
移动端已适配
