### ISSUE TITLE
大哥 你这个webpack打包配置不能直接根据环境切参数嘛

### ISSUE THREAD

**Issue by DDDsergio** [heyongsheng/hevue-img-preview#9]
webpack.config.js ↓
为啥要特地写这样
// entry: './src/main.js', // 本地运行用这个
entry: "./src/lib/index.js", // 线上打包用这个

这么改行不行

const isProd=process.env.NODE_ENV==='production';

module.exports = {
entry: isProd?"./src/lib/index.js":'./src/main.js',

**Comment by heyongsheng** [comment]
哈哈哈，可以可以，那时候还不会这么写，后来就忘了改了，回头就给改了

**Comment by DDDsergio** [comment]
你这一手整的我都有点蒙:)
